{% set name = "gpgme" %}
{% set version = "1.18.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/gpgme/gpgme-{{ version }}.tar.bz2
  sha256: 361d4eae47ce925dba0ea569af40e7b52c645c4ae2e65e5621bf1b6cdd8b0e9e

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - libassuan >=2.4.2,<3
    - libgpg-error >=1.36
  run:
    - libgpg-error >=1.36
    - libassuan >=2.4.2

test:
  commands:
    - test -f $PREFIX/lib/libgpgme${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/gpgme.h  # [unix]
    - test -f $PREFIX/bin/gpgme-config  # [unix]
    - gpgme-tool --help


about:
  home: https://gnupg.org/software/gpgme/index.html
  license: GPL-2.0-or-later AND LGPL-2.1-or-later AND MIT
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSES
  summary: GnuPG Made Easy (GPGME) is a library designed to make access to GnuPG easier for applications.

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - scopatz
