{% set name = "gpgme" %}
{% set version = "1.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/gpgme/gpgme-{{ version }}.tar.bz2
  sha256: cb58494dc415fba9eeb12b826550ad3190dc92e265c5bb2ae1a21c92841cfd38

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
  host:
    - libgpg-error >=1.24
    - libassuan >=2.4.2
  run:
    - libgpg-error >=1.24
    - libassuan >=2.4.2

test:
  commands:
    - test -f $PREFIX/lib/libgpgme${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/gpgme.h  # [unix]
    - test -f $PREFIX/bin/gpgme-config  # [unix]
    - gpgme-tool --help


about:
  home: https://gnupg.org/software/gpgme/index.html
  license: GPL-2.1-or-later AND LGPL-2.1-or-later AND MIT
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSES
  summary: GnuPG Made Easy (GPGME) is a library designed to make access to GnuPG easier for applications.

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - scopatz
