schema_version: 1

context:
  name: gpgme
  version: "2.1.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/gpgme/gpgme-${{ version }}.tar.bz2
  sha256: 0687a95b299871c4141f507c0f740de6b429c9ac067d0fa4e062e3264df5fb77

build:
  number: 0
  skip: win

requirements:
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}
  build:
    - if: unix
      then:
        - gnuconfig
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - make
    - autoconf
  host:
    - libgpg-error >=1.36
    - libassuan >=2.4.2
  run:
    - libgpg-error >=1.36
    - libassuan >=2.4.2

tests:
  - package_contents:
      lib:
        - gpgme
      include:
        - gpgme.h
      files:
        - lib/pkgconfig/gpgme.pc
  - script:
      - gpgme-tool --help

about:
  homepage: https://gnupg.org/software/gpgme/index.html
  license: GPL-2.0-or-later AND LGPL-2.1-or-later AND MIT
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSES
  summary: GnuPG Made Easy (GPGME) is a library designed to make access to GnuPG easier for applications.

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - scopatz
